spring:
  application:
    name: product-manager-api
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
external:
  api:
    url: http://localhost:8081/api/fproducts
app:
  import:
    interval: 60000
# 1 минута для теста